# Generated by Django 3.2.14 on 2022-08-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractionalvalue',
            name='name',
            field=models.FloatField(),
        ),
    ]
