# Generated by Django 3.2.14 on 2022-08-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220809_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractionalvalue',
            name='answer',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='fractionalvalue',
            name='name',
            field=models.FloatField(default='1.0'),
        ),
    ]
